name: PR Check

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review
    paths-ignore:
      - "**/*.md"
      - "LICENSE"

permissions:
  contents: read

concurrency:
  group: pr-check-${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  pr-validate:
    name: PR Validate
    if: ${{ !github.event.pull_request.draft }}
    uses: ./.github/workflows/_validate.yml
